# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/apere594/final-project-zalam007-apere594-jnguy887-dwong133

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/apere594/final-project-zalam007-apere594-jnguy887-dwong133

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/apere594/final-project-zalam007-apere594-jnguy887-dwong133/CMakeFiles /home/csmajs/apere594/final-project-zalam007-apere594-jnguy887-dwong133//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/apere594/final-project-zalam007-apere594-jnguy887-dwong133/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PlayerTester

# Build rule for target.
PlayerTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PlayerTester
.PHONY : PlayerTester

# fast build rule for target.
PlayerTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlayerTester.dir/build.make CMakeFiles/PlayerTester.dir/build
.PHONY : PlayerTester/fast

#=============================================================================
# Target rules for targets named ItemTester

# Build rule for target.
ItemTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ItemTester
.PHONY : ItemTester

# fast build rule for target.
ItemTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ItemTester.dir/build.make CMakeFiles/ItemTester.dir/build
.PHONY : ItemTester/fast

#=============================================================================
# Target rules for targets named MythikinTester

# Build rule for target.
MythikinTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MythikinTester
.PHONY : MythikinTester

# fast build rule for target.
MythikinTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythikinTester.dir/build.make CMakeFiles/MythikinTester.dir/build
.PHONY : MythikinTester/fast

#=============================================================================
# Target rules for targets named MythidexTester

# Build rule for target.
MythidexTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MythidexTester
.PHONY : MythidexTester

# fast build rule for target.
MythidexTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/build
.PHONY : MythidexTester/fast

#=============================================================================
# Target rules for targets named AttackTester

# Build rule for target.
AttackTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AttackTester
.PHONY : AttackTester

# fast build rule for target.
AttackTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AttackTester.dir/build.make CMakeFiles/AttackTester.dir/build
.PHONY : AttackTester/fast

#=============================================================================
# Target rules for targets named BattleTester

# Build rule for target.
BattleTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BattleTester
.PHONY : BattleTester

# fast build rule for target.
BattleTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/build
.PHONY : BattleTester/fast

#=============================================================================
# Target rules for targets named WildBattleTester

# Build rule for target.
WildBattleTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WildBattleTester
.PHONY : WildBattleTester

# fast build rule for target.
WildBattleTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/build
.PHONY : WildBattleTester/fast

#=============================================================================
# Target rules for targets named PCTester

# Build rule for target.
PCTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PCTester
.PHONY : PCTester

# fast build rule for target.
PCTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCTester.dir/build.make CMakeFiles/PCTester.dir/build
.PHONY : PCTester/fast

#=============================================================================
# Target rules for targets named LocationTester

# Build rule for target.
LocationTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LocationTester
.PHONY : LocationTester

# fast build rule for target.
LocationTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocationTester.dir/build.make CMakeFiles/LocationTester.dir/build
.PHONY : LocationTester/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/Battle.o: src/Battle.cpp.o
.PHONY : src/Battle.o

# target to build an object file
src/Battle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Battle.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Battle.cpp.o
.PHONY : src/Battle.cpp.o

src/Battle.i: src/Battle.cpp.i
.PHONY : src/Battle.i

# target to preprocess a source file
src/Battle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Battle.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Battle.cpp.i
.PHONY : src/Battle.cpp.i

src/Battle.s: src/Battle.cpp.s
.PHONY : src/Battle.s

# target to generate assembly for a file
src/Battle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Battle.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Battle.cpp.s
.PHONY : src/Battle.cpp.s

src/BattleMenu.o: src/BattleMenu.cpp.o
.PHONY : src/BattleMenu.o

# target to build an object file
src/BattleMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/BattleMenu.cpp.o
.PHONY : src/BattleMenu.cpp.o

src/BattleMenu.i: src/BattleMenu.cpp.i
.PHONY : src/BattleMenu.i

# target to preprocess a source file
src/BattleMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/BattleMenu.cpp.i
.PHONY : src/BattleMenu.cpp.i

src/BattleMenu.s: src/BattleMenu.cpp.s
.PHONY : src/BattleMenu.s

# target to generate assembly for a file
src/BattleMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/BattleMenu.cpp.s
.PHONY : src/BattleMenu.cpp.s

src/Character.o: src/Character.cpp.o
.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i
.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s
.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/GameplayMenu.o: src/GameplayMenu.cpp.o
.PHONY : src/GameplayMenu.o

# target to build an object file
src/GameplayMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/GameplayMenu.cpp.o
.PHONY : src/GameplayMenu.cpp.o

src/GameplayMenu.i: src/GameplayMenu.cpp.i
.PHONY : src/GameplayMenu.i

# target to preprocess a source file
src/GameplayMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/GameplayMenu.cpp.i
.PHONY : src/GameplayMenu.cpp.i

src/GameplayMenu.s: src/GameplayMenu.cpp.s
.PHONY : src/GameplayMenu.s

# target to generate assembly for a file
src/GameplayMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/GameplayMenu.cpp.s
.PHONY : src/GameplayMenu.cpp.s

src/Gym.o: src/Gym.cpp.o
.PHONY : src/Gym.o

# target to build an object file
src/Gym.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Gym.cpp.o
.PHONY : src/Gym.cpp.o

src/Gym.i: src/Gym.cpp.i
.PHONY : src/Gym.i

# target to preprocess a source file
src/Gym.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Gym.cpp.i
.PHONY : src/Gym.cpp.i

src/Gym.s: src/Gym.cpp.s
.PHONY : src/Gym.s

# target to generate assembly for a file
src/Gym.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Gym.cpp.s
.PHONY : src/Gym.cpp.s

src/ItemShopMenu.o: src/ItemShopMenu.cpp.o
.PHONY : src/ItemShopMenu.o

# target to build an object file
src/ItemShopMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/ItemShopMenu.cpp.o
.PHONY : src/ItemShopMenu.cpp.o

src/ItemShopMenu.i: src/ItemShopMenu.cpp.i
.PHONY : src/ItemShopMenu.i

# target to preprocess a source file
src/ItemShopMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/ItemShopMenu.cpp.i
.PHONY : src/ItemShopMenu.cpp.i

src/ItemShopMenu.s: src/ItemShopMenu.cpp.s
.PHONY : src/ItemShopMenu.s

# target to generate assembly for a file
src/ItemShopMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/ItemShopMenu.cpp.s
.PHONY : src/ItemShopMenu.cpp.s

src/Location.o: src/Location.cpp.o
.PHONY : src/Location.o

# target to build an object file
src/Location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Location.cpp.o
.PHONY : src/Location.cpp.o

src/Location.i: src/Location.cpp.i
.PHONY : src/Location.i

# target to preprocess a source file
src/Location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Location.cpp.i
.PHONY : src/Location.cpp.i

src/Location.s: src/Location.cpp.s
.PHONY : src/Location.s

# target to generate assembly for a file
src/Location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Location.cpp.s
.PHONY : src/Location.cpp.s

src/Mythicenter.o: src/Mythicenter.cpp.o
.PHONY : src/Mythicenter.o

# target to build an object file
src/Mythicenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicenter.cpp.o
.PHONY : src/Mythicenter.cpp.o

src/Mythicenter.i: src/Mythicenter.cpp.i
.PHONY : src/Mythicenter.i

# target to preprocess a source file
src/Mythicenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicenter.cpp.i
.PHONY : src/Mythicenter.cpp.i

src/Mythicenter.s: src/Mythicenter.cpp.s
.PHONY : src/Mythicenter.s

# target to generate assembly for a file
src/Mythicenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicenter.cpp.s
.PHONY : src/Mythicenter.cpp.s

src/Mythicube.o: src/Mythicube.cpp.o
.PHONY : src/Mythicube.o

# target to build an object file
src/Mythicube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicube.cpp.o
.PHONY : src/Mythicube.cpp.o

src/Mythicube.i: src/Mythicube.cpp.i
.PHONY : src/Mythicube.i

# target to preprocess a source file
src/Mythicube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicube.cpp.i
.PHONY : src/Mythicube.cpp.i

src/Mythicube.s: src/Mythicube.cpp.s
.PHONY : src/Mythicube.s

# target to generate assembly for a file
src/Mythicube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythicube.cpp.s
.PHONY : src/Mythicube.cpp.s

src/Mythidex.o: src/Mythidex.cpp.o
.PHONY : src/Mythidex.o

# target to build an object file
src/Mythidex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/src/Mythidex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythidex.cpp.o
.PHONY : src/Mythidex.cpp.o

src/Mythidex.i: src/Mythidex.cpp.i
.PHONY : src/Mythidex.i

# target to preprocess a source file
src/Mythidex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/src/Mythidex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythidex.cpp.i
.PHONY : src/Mythidex.cpp.i

src/Mythidex.s: src/Mythidex.cpp.s
.PHONY : src/Mythidex.s

# target to generate assembly for a file
src/Mythidex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/src/Mythidex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythidex.cpp.s
.PHONY : src/Mythidex.cpp.s

src/Mythishop.o: src/Mythishop.cpp.o
.PHONY : src/Mythishop.o

# target to build an object file
src/Mythishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythishop.cpp.o
.PHONY : src/Mythishop.cpp.o

src/Mythishop.i: src/Mythishop.cpp.i
.PHONY : src/Mythishop.i

# target to preprocess a source file
src/Mythishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythishop.cpp.i
.PHONY : src/Mythishop.cpp.i

src/Mythishop.s: src/Mythishop.cpp.s
.PHONY : src/Mythishop.s

# target to generate assembly for a file
src/Mythishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Mythishop.cpp.s
.PHONY : src/Mythishop.cpp.s

src/NPC.o: src/NPC.cpp.o
.PHONY : src/NPC.o

# target to build an object file
src/NPC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/NPC.cpp.o
.PHONY : src/NPC.cpp.o

src/NPC.i: src/NPC.cpp.i
.PHONY : src/NPC.i

# target to preprocess a source file
src/NPC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/NPC.cpp.i
.PHONY : src/NPC.cpp.i

src/NPC.s: src/NPC.cpp.s
.PHONY : src/NPC.s

# target to generate assembly for a file
src/NPC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/NPC.cpp.s
.PHONY : src/NPC.cpp.s

src/PC.o: src/PC.cpp.o
.PHONY : src/PC.o

# target to build an object file
src/PC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/PC.cpp.o
.PHONY : src/PC.cpp.o

src/PC.i: src/PC.cpp.i
.PHONY : src/PC.i

# target to preprocess a source file
src/PC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/PC.cpp.i
.PHONY : src/PC.cpp.i

src/PC.s: src/PC.cpp.s
.PHONY : src/PC.s

# target to generate assembly for a file
src/PC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/PC.cpp.s
.PHONY : src/PC.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Potion.o: src/Potion.cpp.o
.PHONY : src/Potion.o

# target to build an object file
src/Potion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Potion.cpp.o
.PHONY : src/Potion.cpp.o

src/Potion.i: src/Potion.cpp.i
.PHONY : src/Potion.i

# target to preprocess a source file
src/Potion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Potion.cpp.i
.PHONY : src/Potion.cpp.i

src/Potion.s: src/Potion.cpp.s
.PHONY : src/Potion.s

# target to generate assembly for a file
src/Potion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Potion.cpp.s
.PHONY : src/Potion.cpp.s

src/Team.o: src/Team.cpp.o
.PHONY : src/Team.o

# target to build an object file
src/Team.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Team.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Team.cpp.o
.PHONY : src/Team.cpp.o

src/Team.i: src/Team.cpp.i
.PHONY : src/Team.i

# target to preprocess a source file
src/Team.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Team.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Team.cpp.i
.PHONY : src/Team.cpp.i

src/Team.s: src/Team.cpp.s
.PHONY : src/Team.s

# target to generate assembly for a file
src/Team.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/src/Team.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/Team.cpp.s
.PHONY : src/Team.cpp.s

src/WildBattle.o: src/WildBattle.cpp.o
.PHONY : src/WildBattle.o

# target to build an object file
src/WildBattle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattle.cpp.o
.PHONY : src/WildBattle.cpp.o

src/WildBattle.i: src/WildBattle.cpp.i
.PHONY : src/WildBattle.i

# target to preprocess a source file
src/WildBattle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattle.cpp.i
.PHONY : src/WildBattle.cpp.i

src/WildBattle.s: src/WildBattle.cpp.s
.PHONY : src/WildBattle.s

# target to generate assembly for a file
src/WildBattle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattle.cpp.s
.PHONY : src/WildBattle.cpp.s

src/WildBattleMenu.o: src/WildBattleMenu.cpp.o
.PHONY : src/WildBattleMenu.o

# target to build an object file
src/WildBattleMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattleMenu.cpp.o
.PHONY : src/WildBattleMenu.cpp.o

src/WildBattleMenu.i: src/WildBattleMenu.cpp.i
.PHONY : src/WildBattleMenu.i

# target to preprocess a source file
src/WildBattleMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattleMenu.cpp.i
.PHONY : src/WildBattleMenu.cpp.i

src/WildBattleMenu.s: src/WildBattleMenu.cpp.s
.PHONY : src/WildBattleMenu.s

# target to generate assembly for a file
src/WildBattleMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildBattleMenu.cpp.s
.PHONY : src/WildBattleMenu.cpp.s

src/WildLocation.o: src/WildLocation.cpp.o
.PHONY : src/WildLocation.o

# target to build an object file
src/WildLocation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildLocation.cpp.o
.PHONY : src/WildLocation.cpp.o

src/WildLocation.i: src/WildLocation.cpp.i
.PHONY : src/WildLocation.i

# target to preprocess a source file
src/WildLocation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildLocation.cpp.i
.PHONY : src/WildLocation.cpp.i

src/WildLocation.s: src/WildLocation.cpp.s
.PHONY : src/WildLocation.s

# target to generate assembly for a file
src/WildLocation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/src/WildLocation.cpp.s
.PHONY : src/WildLocation.cpp.s

testing/AttackTester.o: testing/AttackTester.cpp.o
.PHONY : testing/AttackTester.o

# target to build an object file
testing/AttackTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AttackTester.dir/build.make CMakeFiles/AttackTester.dir/testing/AttackTester.cpp.o
.PHONY : testing/AttackTester.cpp.o

testing/AttackTester.i: testing/AttackTester.cpp.i
.PHONY : testing/AttackTester.i

# target to preprocess a source file
testing/AttackTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AttackTester.dir/build.make CMakeFiles/AttackTester.dir/testing/AttackTester.cpp.i
.PHONY : testing/AttackTester.cpp.i

testing/AttackTester.s: testing/AttackTester.cpp.s
.PHONY : testing/AttackTester.s

# target to generate assembly for a file
testing/AttackTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AttackTester.dir/build.make CMakeFiles/AttackTester.dir/testing/AttackTester.cpp.s
.PHONY : testing/AttackTester.cpp.s

testing/BattleTester.o: testing/BattleTester.cpp.o
.PHONY : testing/BattleTester.o

# target to build an object file
testing/BattleTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/testing/BattleTester.cpp.o
.PHONY : testing/BattleTester.cpp.o

testing/BattleTester.i: testing/BattleTester.cpp.i
.PHONY : testing/BattleTester.i

# target to preprocess a source file
testing/BattleTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/testing/BattleTester.cpp.i
.PHONY : testing/BattleTester.cpp.i

testing/BattleTester.s: testing/BattleTester.cpp.s
.PHONY : testing/BattleTester.s

# target to generate assembly for a file
testing/BattleTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BattleTester.dir/build.make CMakeFiles/BattleTester.dir/testing/BattleTester.cpp.s
.PHONY : testing/BattleTester.cpp.s

testing/ItemTester.o: testing/ItemTester.cpp.o
.PHONY : testing/ItemTester.o

# target to build an object file
testing/ItemTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ItemTester.dir/build.make CMakeFiles/ItemTester.dir/testing/ItemTester.cpp.o
.PHONY : testing/ItemTester.cpp.o

testing/ItemTester.i: testing/ItemTester.cpp.i
.PHONY : testing/ItemTester.i

# target to preprocess a source file
testing/ItemTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ItemTester.dir/build.make CMakeFiles/ItemTester.dir/testing/ItemTester.cpp.i
.PHONY : testing/ItemTester.cpp.i

testing/ItemTester.s: testing/ItemTester.cpp.s
.PHONY : testing/ItemTester.s

# target to generate assembly for a file
testing/ItemTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ItemTester.dir/build.make CMakeFiles/ItemTester.dir/testing/ItemTester.cpp.s
.PHONY : testing/ItemTester.cpp.s

testing/LocationTester.o: testing/LocationTester.cpp.o
.PHONY : testing/LocationTester.o

# target to build an object file
testing/LocationTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocationTester.dir/build.make CMakeFiles/LocationTester.dir/testing/LocationTester.cpp.o
.PHONY : testing/LocationTester.cpp.o

testing/LocationTester.i: testing/LocationTester.cpp.i
.PHONY : testing/LocationTester.i

# target to preprocess a source file
testing/LocationTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocationTester.dir/build.make CMakeFiles/LocationTester.dir/testing/LocationTester.cpp.i
.PHONY : testing/LocationTester.cpp.i

testing/LocationTester.s: testing/LocationTester.cpp.s
.PHONY : testing/LocationTester.s

# target to generate assembly for a file
testing/LocationTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocationTester.dir/build.make CMakeFiles/LocationTester.dir/testing/LocationTester.cpp.s
.PHONY : testing/LocationTester.cpp.s

testing/MythidexTester.o: testing/MythidexTester.cpp.o
.PHONY : testing/MythidexTester.o

# target to build an object file
testing/MythidexTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/testing/MythidexTester.cpp.o
.PHONY : testing/MythidexTester.cpp.o

testing/MythidexTester.i: testing/MythidexTester.cpp.i
.PHONY : testing/MythidexTester.i

# target to preprocess a source file
testing/MythidexTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/testing/MythidexTester.cpp.i
.PHONY : testing/MythidexTester.cpp.i

testing/MythidexTester.s: testing/MythidexTester.cpp.s
.PHONY : testing/MythidexTester.s

# target to generate assembly for a file
testing/MythidexTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythidexTester.dir/build.make CMakeFiles/MythidexTester.dir/testing/MythidexTester.cpp.s
.PHONY : testing/MythidexTester.cpp.s

testing/MythikinTester.o: testing/MythikinTester.cpp.o
.PHONY : testing/MythikinTester.o

# target to build an object file
testing/MythikinTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythikinTester.dir/build.make CMakeFiles/MythikinTester.dir/testing/MythikinTester.cpp.o
.PHONY : testing/MythikinTester.cpp.o

testing/MythikinTester.i: testing/MythikinTester.cpp.i
.PHONY : testing/MythikinTester.i

# target to preprocess a source file
testing/MythikinTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythikinTester.dir/build.make CMakeFiles/MythikinTester.dir/testing/MythikinTester.cpp.i
.PHONY : testing/MythikinTester.cpp.i

testing/MythikinTester.s: testing/MythikinTester.cpp.s
.PHONY : testing/MythikinTester.s

# target to generate assembly for a file
testing/MythikinTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MythikinTester.dir/build.make CMakeFiles/MythikinTester.dir/testing/MythikinTester.cpp.s
.PHONY : testing/MythikinTester.cpp.s

testing/PCTester.o: testing/PCTester.cpp.o
.PHONY : testing/PCTester.o

# target to build an object file
testing/PCTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCTester.dir/build.make CMakeFiles/PCTester.dir/testing/PCTester.cpp.o
.PHONY : testing/PCTester.cpp.o

testing/PCTester.i: testing/PCTester.cpp.i
.PHONY : testing/PCTester.i

# target to preprocess a source file
testing/PCTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCTester.dir/build.make CMakeFiles/PCTester.dir/testing/PCTester.cpp.i
.PHONY : testing/PCTester.cpp.i

testing/PCTester.s: testing/PCTester.cpp.s
.PHONY : testing/PCTester.s

# target to generate assembly for a file
testing/PCTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PCTester.dir/build.make CMakeFiles/PCTester.dir/testing/PCTester.cpp.s
.PHONY : testing/PCTester.cpp.s

testing/PlayerTester.o: testing/PlayerTester.cpp.o
.PHONY : testing/PlayerTester.o

# target to build an object file
testing/PlayerTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlayerTester.dir/build.make CMakeFiles/PlayerTester.dir/testing/PlayerTester.cpp.o
.PHONY : testing/PlayerTester.cpp.o

testing/PlayerTester.i: testing/PlayerTester.cpp.i
.PHONY : testing/PlayerTester.i

# target to preprocess a source file
testing/PlayerTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlayerTester.dir/build.make CMakeFiles/PlayerTester.dir/testing/PlayerTester.cpp.i
.PHONY : testing/PlayerTester.cpp.i

testing/PlayerTester.s: testing/PlayerTester.cpp.s
.PHONY : testing/PlayerTester.s

# target to generate assembly for a file
testing/PlayerTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PlayerTester.dir/build.make CMakeFiles/PlayerTester.dir/testing/PlayerTester.cpp.s
.PHONY : testing/PlayerTester.cpp.s

testing/WildBattleTester.o: testing/WildBattleTester.cpp.o
.PHONY : testing/WildBattleTester.o

# target to build an object file
testing/WildBattleTester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/testing/WildBattleTester.cpp.o
.PHONY : testing/WildBattleTester.cpp.o

testing/WildBattleTester.i: testing/WildBattleTester.cpp.i
.PHONY : testing/WildBattleTester.i

# target to preprocess a source file
testing/WildBattleTester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/testing/WildBattleTester.cpp.i
.PHONY : testing/WildBattleTester.cpp.i

testing/WildBattleTester.s: testing/WildBattleTester.cpp.s
.PHONY : testing/WildBattleTester.s

# target to generate assembly for a file
testing/WildBattleTester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WildBattleTester.dir/build.make CMakeFiles/WildBattleTester.dir/testing/WildBattleTester.cpp.s
.PHONY : testing/WildBattleTester.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AttackTester"
	@echo "... BattleTester"
	@echo "... ItemTester"
	@echo "... LocationTester"
	@echo "... MythidexTester"
	@echo "... MythikinTester"
	@echo "... PCTester"
	@echo "... PlayerTester"
	@echo "... WildBattleTester"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/Battle.o"
	@echo "... src/Battle.i"
	@echo "... src/Battle.s"
	@echo "... src/BattleMenu.o"
	@echo "... src/BattleMenu.i"
	@echo "... src/BattleMenu.s"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/GameplayMenu.o"
	@echo "... src/GameplayMenu.i"
	@echo "... src/GameplayMenu.s"
	@echo "... src/Gym.o"
	@echo "... src/Gym.i"
	@echo "... src/Gym.s"
	@echo "... src/ItemShopMenu.o"
	@echo "... src/ItemShopMenu.i"
	@echo "... src/ItemShopMenu.s"
	@echo "... src/Location.o"
	@echo "... src/Location.i"
	@echo "... src/Location.s"
	@echo "... src/Mythicenter.o"
	@echo "... src/Mythicenter.i"
	@echo "... src/Mythicenter.s"
	@echo "... src/Mythicube.o"
	@echo "... src/Mythicube.i"
	@echo "... src/Mythicube.s"
	@echo "... src/Mythidex.o"
	@echo "... src/Mythidex.i"
	@echo "... src/Mythidex.s"
	@echo "... src/Mythishop.o"
	@echo "... src/Mythishop.i"
	@echo "... src/Mythishop.s"
	@echo "... src/NPC.o"
	@echo "... src/NPC.i"
	@echo "... src/NPC.s"
	@echo "... src/PC.o"
	@echo "... src/PC.i"
	@echo "... src/PC.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Potion.o"
	@echo "... src/Potion.i"
	@echo "... src/Potion.s"
	@echo "... src/Team.o"
	@echo "... src/Team.i"
	@echo "... src/Team.s"
	@echo "... src/WildBattle.o"
	@echo "... src/WildBattle.i"
	@echo "... src/WildBattle.s"
	@echo "... src/WildBattleMenu.o"
	@echo "... src/WildBattleMenu.i"
	@echo "... src/WildBattleMenu.s"
	@echo "... src/WildLocation.o"
	@echo "... src/WildLocation.i"
	@echo "... src/WildLocation.s"
	@echo "... testing/AttackTester.o"
	@echo "... testing/AttackTester.i"
	@echo "... testing/AttackTester.s"
	@echo "... testing/BattleTester.o"
	@echo "... testing/BattleTester.i"
	@echo "... testing/BattleTester.s"
	@echo "... testing/ItemTester.o"
	@echo "... testing/ItemTester.i"
	@echo "... testing/ItemTester.s"
	@echo "... testing/LocationTester.o"
	@echo "... testing/LocationTester.i"
	@echo "... testing/LocationTester.s"
	@echo "... testing/MythidexTester.o"
	@echo "... testing/MythidexTester.i"
	@echo "... testing/MythidexTester.s"
	@echo "... testing/MythikinTester.o"
	@echo "... testing/MythikinTester.i"
	@echo "... testing/MythikinTester.s"
	@echo "... testing/PCTester.o"
	@echo "... testing/PCTester.i"
	@echo "... testing/PCTester.s"
	@echo "... testing/PlayerTester.o"
	@echo "... testing/PlayerTester.i"
	@echo "... testing/PlayerTester.s"
	@echo "... testing/WildBattleTester.o"
	@echo "... testing/WildBattleTester.i"
	@echo "... testing/WildBattleTester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

